version: 2
jobs:
   build:
     docker:
       - image: circleci/node:8.9
     steps:
       - checkout
       - run: npm run build
   test:
     docker:
       - image: circleci/node:8.9
     steps:
       - checkout
       - run: npm install
       - run: npm run test
   lint:
     docker:
       - image: circleci/node:8.9
     steps:
       - checkout
       - run: echo "hi there"
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - lint
      - test:
          requires:
            - lint